"""Provider that serves recorded fixture data. Used by tests, CI, and offline demos.

The bundled fixtures are synthetic (generated by ``scripts/make_fixtures.py``), not real
market data.
"""

from __future__ import annotations

import json
from datetime import date, datetime, timedelta
from importlib import resources
from pathlib import Path
from typing import Any

from socagents.core.errors import ProviderError, SymbolNotFound
from socagents.core.timeutil import ET, next_session_open
from socagents.providers.base import (
    Bar,
    BarSeries,
    EconomicEvent,
    EventSet,
    Headline,
    HeadlineSet,
    Mode,
    OptionChain,
    Quote,
    QuoteSet,
)

FIXTURE_PACKAGE = "socagents.providers.fixtures"


class FixtureProvider:
    name = "fixture"
    mode: Mode = "community"

    def __init__(self, data_dir: Path | None = None) -> None:
        self._data_dir = data_dir
        self._cache: dict[str, dict[str, Any]] = {}

    async def aclose(self) -> None:
        return None

    def available_symbols(self) -> list[str]:
        if self._data_dir is not None:
            names = [p.name for p in self._data_dir.glob("*.json")]
        else:
            names = [r.name for r in resources.files(FIXTURE_PACKAGE).iterdir()]
        return sorted(n.removesuffix(".json") for n in names if n.endswith(".json"))

    def _load(self, symbol: str) -> dict[str, Any]:
        symbol = symbol.upper()
        if symbol in self._cache:
            return self._cache[symbol]
        filename = f"{symbol}.json"
        if self._data_dir is not None:
            path = self._data_dir / filename
            if not path.is_file():
                raise SymbolNotFound(f"No fixture data for {symbol}.")
            text = path.read_text(encoding="utf-8")
        else:
            res = resources.files(FIXTURE_PACKAGE).joinpath(filename)
            if not res.is_file():
                raise SymbolNotFound(f"No fixture data for {symbol}.")
            text = res.read_text(encoding="utf-8")
        doc: dict[str, Any] = json.loads(text)
        self._cache[symbol] = doc
        return doc

    def _meta(self, doc: dict[str, Any]) -> dict[str, Any]:
        meta = doc["meta"]
        return {
            "source": meta["source"],
            "as_of": meta["as_of"],
            "delayed_sec": meta["delayed_sec"],
        }

    async def quotes(self, symbols: list[str]) -> QuoteSet:
        if not symbols:
            raise ProviderError("At least one symbol is required.")
        docs = [self._load(s) for s in symbols]
        as_of = min(datetime.fromisoformat(d["meta"]["as_of"]) for d in docs)
        return QuoteSet(
            source=docs[0]["meta"]["source"],
            as_of=as_of,
            delayed_sec=max(int(d["meta"]["delayed_sec"]) for d in docs),
            quotes=[Quote.model_validate(d["quote"]) for d in docs],
        )

    async def option_chain(self, symbol: str, expiration: date | None = None) -> OptionChain:
        doc = self._load(symbol)
        chain = OptionChain.model_validate(
            {
                **self._meta(doc),
                "symbol": symbol.upper(),
                "underlying_price": doc["quote"]["last"],
                "contracts": doc["chain"],
            }
        )
        if expiration is None:
            return chain
        contracts = [c for c in chain.contracts if c.expiration == expiration]
        if not contracts:
            available = ", ".join(d.isoformat() for d in chain.expirations())
            raise ProviderError(
                f"No {symbol.upper()} contracts expire on {expiration.isoformat()}. "
                f"Available: {available}.",
                code="expiration_not_found",
            )
        return chain.model_copy(update={"contracts": contracts})

    async def bars(self, symbol: str, interval: str = "5m", lookback: int = 78) -> BarSeries:
        doc = self._load(symbol)
        series = doc["bars"]
        if interval != series["interval"]:
            raise ProviderError(
                f"Fixture data has only {series['interval']} bars.", code="interval_not_available"
            )
        bars = [Bar.model_validate(b) for b in series["bars"]][-lookback:]
        return BarSeries(
            **self._meta(doc), symbol=symbol.upper(), interval=series["interval"], bars=bars
        )

    async def headlines(self, symbol: str, limit: int = 10) -> HeadlineSet:
        doc = self._load(symbol)
        items = [Headline.model_validate(h) for h in doc.get("headlines", [])][:limit]
        return HeadlineSet(**self._meta(doc), symbol=symbol.upper(), headlines=items)

    async def events(self, hours: int = 48) -> EventSet:
        symbols = self.available_symbols()
        if not symbols:
            raise ProviderError("No fixture data is installed.")
        doc = self._load(symbols[0])
        start = datetime.fromisoformat(doc["meta"]["as_of"])
        end = start + timedelta(hours=hours)
        if start.astimezone(ET).weekday() >= 5:  # Sat/Sun: see community.py's events()
            end = max(end, next_session_open(start) + timedelta(hours=hours))
        events = [EconomicEvent.model_validate(e) for e in doc.get("events", [])]
        return EventSet(**self._meta(doc), events=[e for e in events if start <= e.time <= end])
